name: continuous-integration

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-on-fast: fail the matrix build if any matrix jobs fail
      fail-fast: true
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
        cxx: [g++-10, clang++]
        method: [CPMFindPackage, FetchContent, find-package, git-submodule]
        exclude:
          - os: windows-2019
            # doesn't actually matter which windows build we exclude since it
            # pays no attention to either CXX option, but we don't want to run
            # the same build twice so we still exclude one of them.
            cxx: clang++

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        if: ${{ matrix.method == 'find-package' || matrix.method == 'git-submodule' }}
        shell: bash
        run: git submodule update --init

      - name: Install SDL
        env:
          OS: ${{ matrix.os }}
        if: ${{ matrix.method == 'find-package' }}
        shell: bash
        run: |
          mkdir build-sdl
          cd build-sdl
          cmake $GITHUB_WORKSPACE/test-git-submodule/SDL -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j4 --config Release
          if [ $OS != 'windows-2019' ]; then sudo cmake --install . --config Release; else cmake --install . --config Release; fi

      - name: Build
        env:
          CXX: ${{ matrix.cxx }}
          METHOD: ${{ matrix.method }}
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE/test-$METHOD -DCMAKE_BUILD_TYPE=Debug
          cmake --build . -j4 --config Debug
          ctest --no-tests=error -C Debug
