name: continuous-integration

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-on-fast: fail the matrix build if any matrix jobs fail
      fail-fast: true
      matrix:
        os: [macos-10.15, ubuntu-20.04]
        cxx: [g++-10, clang++]
        method: [CPMFindPackage, FetchContent, find-package, git-submodule]
        include:
          - os: windows-2019
            cxx: msvc

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        if: ${{ matrix.method }} == 'find-package' || ${{ matrix.method }} == 'git-submodule'
        shell: bash
        run: git submodule update --init

      - name: Install SDL
        if: ${{ matrix.method }} == 'find-package'
        shell: bash
        run: |
          mkdir build-sdl
          cd build-sdl
          cmake $GITHUB_WORKSPACE/test-git-submodule/SDL
          cmake --build . -j4
          cmake --install .

      - name: Build
        env:
          CXX: ${{ matrix.cxx }}
          METHOD: ${{ matrix.method }}
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE/test-$METHOD
          cmake --build . -j4
          ctest --no-tests=error
